[package]
name = "cspice-rs"
version = "0.1.0"
edition = "2021"
license = "LGPL-3.0"
rust-version = "1.77"
authors = ["Jacob Halsey <jacob@jhalsey.com>", "cislunarspace", "Contributors"]
homepage = "https://github.com/cislunarspace/cspice-rs/tree/main/cspice"
repository = "https://github.com/cislunarspace/cspice-rs"

[dependencies]
chrono = { version = "0.4.19", optional = true }
cspice-rs-sys = { path = "../cspice-sys", version = "0.1.0" }
derive_more = "0.99.17"
parking_lot = "0.12.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_plain = "1.0.0"
thiserror = "2.0.21"
