[package]
name = "cspice-rs-sys"
version = "0.1.0"
edition = "2021"
build = "build.rs"
description = "Unsafe bindings to the NAIF CSPICE toolkit"
license = "LGPL-3.0"
authors = ["Jacob Halsey <jacob@jhalsey.com>", "cislunarspace"]
homepage = "https://github.com/cislunarspace/cspice-rs/tree/main/cspice-sys"
repository = "https://github.com/cislunarspace/cspice-rs"
rust-version = "1.77"

[features]
downloadcspice = ["dep:reqwest"]

[dependencies]

[build-dependencies]
bindgen = "0.73"
reqwest = { version = "0.12", features = ["blocking"], optional = true }
